# Generated by Django 4.2.16 on 2024-11-01 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formatos', '0002_alter_registrofopep_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrofopep',
            name='code',
            field=models.CharField(max_length=173),
        ),
    ]
